version: "3.3"

services:
  frontend:
    image: 978577353296.dkr.ecr.eu-west-1.amazonaws.com/skeleton-ui:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        - NPM_AUTH
