---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dev-skeleton-ui
  name: dev-skeleton-ui
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dev-skeleton-ui
    spec:
      containers:
      - name: app
        image: 978577353296.dkr.ecr.eu-west-1.amazonaws.com/skeleton-ui:APPIMAGEPLACEHOLDER
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-secrets
              key: GOOGLE_CLIENT_ID
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: API_URL
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 500Mi
      restartPolicy: Always

      imagePullSecrets:
        - name: eu-west-1-ecr-registry
